name: Create Release PR - sample-package-npm-scoped

on: workflow_dispatch

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample-package-npm-scoped

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: npm

      - run: npm ci

      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - run: npx shipjs prepare -y
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
