name: Release
on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample-package-npm-scoped

    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: npm
          cache-dependency-path: "**/package-lock.json"
          registry-url: "https://registry.npmjs.org"
          scope: "@tyankatsu0105"

      - run: npm ci

      - run: npx shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
